# Stage 1 - build app
FROM node:16.19.0-alpine3.17 as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run nx test frontend-app
RUN npm run nx build frontend-app

# Stage 2
FROM nginx:alpine
COPY --from=node /app/dist/apps/frontend-app /usr/share/nginx/html