version: '3.8'

services:
    api:
        container_name: api
        image: api:1.0.0
        build:
            context: .
            dockerfile: ./apps/api-app/Dockerfile.backend
        ports:
            - 3333:3333
        networks:
            - app-network
        restart: unless-stopped
    app:
        container_name: app
        image: app:1.0.0
        build:
            context: .
            dockerfile: ./apps/frontend-app/Dockerfile.frontend
        ports:
            - 8080:80
        volumes:
            - ./apps/frontend-app/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        restart: unless-stopped
        depends_on:
            - api

networks:
    app-network: